"""Top ~4500 most frequent English words — almost always terrible category names."""
COMMON_ENGLISH_WORDS: set[str] = {
    "Africa", "British", "England", "English", "Europe", "France", "French", "God", "Greek",
    "Japanese", "Washington", "a", "able", "about", "above", "accept", "accepted", "account",
    "across", "act", "action", "actually", "add", "added", "addition", "adjective", "admit",
    "affect", "afraid", "after", "again", "against", "age", "ago", "agree", "agreed", "ahead",
    "air", "all", "allow", "allowed", "almost", "alone", "along", "already", "also",
    "although", "always", "am", "among", "amount", "an", "and", "angle", "animal", "another",
    "answer", "any", "anyone", "anything", "anyway", "appear", "apple", "apply", "approach",
    "are", "area", "arm", "arms", "army", "around", "arrive", "arrived", "art", "article",
    "as", "ask", "at", "attack", "available", "avoid", "away", "baby", "back", "bad", "ball",
    "bank", "bar", "base", "be", "bear", "beat", "beautiful", "became", "become", "bed",
    "been", "before", "began", "begin", "behind", "being", "believe", "bell", "belong",
    "below", "benefit", "beside", "best", "better", "between", "beyond", "big", "bill",
    "birds", "bit", "black", "block", "blood", "blow", "blue", "board", "boat", "body",
    "bones", "book", "born", "both", "bottom", "bought", "box", "boy", "branches", "break",
    "bright", "bring", "broken", "brother", "brought", "brown", "build", "building", "built",
    "burn", "burning", "business", "busy", "but", "buy", "by", "call", "came", "camp", "can",
    "can't", "cannot", "capital", "captain", "car", "card", "care", "carefully", "carry",
    "case", "cat", "catch", "cattle", "caught", "cause", "cell", "cells", "center", "central",
    "cents", "century", "certain", "chance", "change", "chart", "check", "chief", "child",
    "children", "choice", "choose", "church", "circle", "city", "claim", "claimed", "claims",
    "class", "clean", "clear", "climb", "climbed", "close", "clothes", "cloud", "club",
    "coal", "coast", "coat", "cold", "college", "color", "column", "come", "common",
    "company", "compare", "complete", "compound", "condition", "conditions", "consider",
    "contain", "continue", "continued", "control", "cook", "cool", "copy", "corn", "corner",
    "correct", "cost", "cotton", "could", "couldn't", "count", "country", "course", "court",
    "cover", "covered", "cows", "create", "cried", "crops", "cross", "crowd", "cry", "cup",
    "current", "cut", "dance", "danger", "dark", "daughter", "day", "dead", "deal", "death",
    "decide", "decided", "decimal", "deep", "defense", "demand", "describe", "desert",
    "design", "detail", "details", "determine", "develop", "developed", "dictionary", "did",
    "didn't", "die", "died", "difference", "different", "difficult", "dinner", "direct",
    "direction", "discover", "discovered", "discuss", "disease", "distance", "divided",
    "division", "do", "doctor", "does", "doesn't", "dog", "dollars", "don't", "done", "door",
    "double", "doubt", "down", "draw", "drawing", "dream", "dress", "drink", "drive", "drop",
    "dry", "during", "duty", "each", "early", "ears", "earth", "east", "easy", "eat", "edge",
    "effect", "effort", "egg", "eggs", "eight", "either", "electric", "elements", "else",
    "empty", "end", "enemy", "energy", "engine", "enjoy", "enough", "enter", "entered",
    "entire", "equal", "equation", "escape", "especially", "even", "evening", "event", "ever",
    "every", "everyone", "everything", "exactly", "example", "except", "excite", "exciting",
    "exercise", "exist", "expect", "experience", "experiment", "explain", "express", "eye",
    "face", "fact", "factories", "factors", "fail", "fair", "fall", "family", "famous", "far",
    "farm", "farmers", "fast", "fat", "father", "fear", "feed", "feel", "feeling", "feet",
    "fell", "felt", "few", "field", "fig", "fight", "figure", "fill", "filled", "final",
    "finally", "find", "fine", "finger", "fingers", "finish", "finished", "fire", "firm",
    "first", "fish", "fit", "five", "fix", "flat", "floor", "flow", "flower", "flowers",
    "fly", "follow", "food", "foot", "for", "force", "foreign", "forest", "form", "former",
    "forward", "found", "four", "fraction", "frame", "free", "freedom", "fresh", "friend",
    "friends", "from", "front", "fruit", "full", "fun", "further", "future", "game", "garden",
    "gas", "gave", "general", "get", "gift", "girl", "give", "glad", "glass", "go", "gold",
    "gone", "good", "got", "government", "grass", "gray", "great", "green", "grew", "ground",
    "group", "grow", "growth", "guard", "guess", "gun", "had", "hair", "half", "hall", "halt",
    "hand", "hang", "happen", "happened", "happy", "hard", "has", "hat", "hate", "have",
    "head", "health", "hear", "heard", "heart", "heat", "heavy", "held", "help", "her",
    "here", "herself", "hide", "high", "hill", "him", "himself", "his", "history", "hit",
    "hold", "hole", "home", "hope", "horse", "hospital", "hot", "hotel", "hour", "hours",
    "house", "how", "however", "huge", "human", "hundred", "hungry", "hunt", "hunting",
    "hurry", "hurt", "husband", "i'll", "ice", "idea", "if", "imagine", "important", "in",
    "inches", "include", "increase", "indeed", "indicate", "industry", "information",
    "insects", "inside", "instead", "instruments", "interest", "interesting", "into", "iron",
    "is", "island", "isn't", "issue", "it", "it's", "its", "itself", "job", "join", "joined",
    "jump", "jumped", "just", "keep", "kept", "key", "kill", "killed", "kind", "king", "kiss",
    "kitchen", "knew", "knife", "knock", "know", "known", "lady", "laid", "lake", "land",
    "language", "large", "last", "late", "laugh", "laughed", "law", "lay", "lead", "learn",
    "least", "leave", "led", "left", "leg", "legs", "length", "less", "let", "let's",
    "letter", "level", "lie", "life", "lift", "lifted", "light", "like", "line", "lip",
    "list", "listen", "little", "live", "load", "local", "located", "lonely", "long", "look",
    "lose", "loss", "lost", "lot", "loud", "love", "low", "luck", "lunch", "machine", "made",
    "main", "major", "majority", "make", "man", "manage", "many", "map", "march", "mark",
    "market", "master", "match", "material", "matter", "may", "maybe", "me", "meal", "mean",
    "measure", "meat", "media", "medical", "meet", "melody", "member", "members", "men",
    "mention", "message", "metal", "method", "middle", "might", "mile", "milk", "million",
    "mind", "mine", "minute", "minutes", "miss", "mistake", "mister", "mix", "model",
    "modern", "molecules", "moment", "money", "month", "months", "moon", "more", "morning",
    "most", "mother", "motion", "motor", "mountain", "mouth", "move", "movement", "movie",
    "much", "murder", "music", "must", "my", "myself", "name", "narrow", "nation", "natural",
    "nature", "near", "necessary", "neck", "need", "neighbor", "neither", "network", "never",
    "new", "news", "next", "nice", "night", "nine", "no", "nobody", "noise", "none", "nor",
    "normal", "north", "northern", "nose", "not", "note", "nothing", "notice", "noun", "now",
    "number", "numeral", "object", "observe", "ocean", "of", "off", "offer", "office",
    "officer", "official", "often", "oh", "oil", "old", "on", "once", "one", "oneself",
    "only", "open", "operation", "opinion", "opposite", "or", "order", "ordinary",
    "organization", "original", "other", "our", "out", "outside", "over", "own", "owner",
    "oxygen", "pack", "page", "pain", "paint", "pair", "pal", "paper", "paragraph", "parent",
    "park", "part", "particular", "partner", "party", "pass", "passed", "past", "patient",
    "pattern", "pay", "peace", "people", "per", "perhaps", "period", "person", "phone",
    "phrase", "pick", "picked", "picture", "piece", "place", "plains", "plan", "plane",
    "planets", "plant", "plate", "play", "please", "plural", "pocket", "poem", "point",
    "pole", "police", "policy", "political", "poor", "popular", "position", "positive",
    "possible", "post", "pounds", "power", "practice", "prepare", "prepared", "present",
    "president", "press", "pressure", "pretty", "prevent", "price", "printed", "private",
    "probably", "problem", "process", "produce", "product", "products", "professional",
    "professor", "program", "project", "property", "protect", "prove", "provide", "public",
    "pull", "pulled", "purpose", "push", "pushed", "put", "quality", "question", "quick",
    "quickly", "quiet", "quite", "race", "radio", "rain", "raise", "raised", "ran", "range",
    "rate", "rather", "reach", "reached", "read", "ready", "real", "reason", "receive",
    "received", "recent", "record", "red", "reflect", "region", "relation", "remain",
    "remember", "remove", "repeat", "repeated", "report", "represent", "require", "research",
    "resource", "rest", "result", "return", "rhythm", "rich", "ride", "right", "ring", "rise",
    "risk", "river", "road", "rock", "role", "roll", "rolled", "roof", "room", "root", "rope",
    "rose", "round", "row", "rule", "run", "sad", "safe", "said", "sail", "salt", "same",
    "sand", "sat", "save", "saw", "say", "scale", "scene", "school", "science", "scientist",
    "scientists", "score", "sea", "search", "season", "seat", "second", "secret", "section",
    "security", "see", "seeds", "seek", "seem", "seen", "select", "sell", "send", "senior",
    "sense", "sent", "sentence", "separate", "serious", "serve", "service", "set", "settle",
    "settled", "seven", "several", "sex", "shadow", "shake", "shall", "shape", "share",
    "sharp", "she", "sheet", "ship", "shirt", "shoe", "shoes", "shoot", "shop", "short",
    "shot", "should", "shoulder", "shout", "shouted", "show", "shown", "shut", "sick", "side",
    "sight", "sign", "silence", "silent", "similar", "simple", "simply", "since", "sing",
    "single", "sir", "sister", "sit", "situation", "six", "size", "skill", "skin", "sky",
    "sleep", "slow", "slowly", "small", "smell", "smile", "smiled", "smoke", "snow",
    "snowflakes", "so", "social", "society", "soft", "soil", "soldier", "soldiers", "solid",
    "solution", "solve", "some", "somebody", "somehow", "someone", "something", "sometimes",
    "son", "song", "soon", "sorrow", "sort", "sound", "south", "southern", "space", "speak",
    "special", "specific", "speech", "speed", "spell", "spend", "sport", "spot", "spread",
    "spring", "square", "staff", "stage", "stair", "stand", "standard", "standing", "stands",
    "star", "stars", "start", "state", "statement", "station", "stay", "steal", "steam",
    "steel", "step", "stick", "still", "stock", "stomach", "stone", "stood", "stop", "store",
    "storm", "story", "straight", "strange", "strategy", "stream", "street", "stretch",
    "stretched", "strike", "string", "strip", "strong", "structure", "struggle", "student",
    "students", "study", "stuff", "stupid", "style", "subject", "substances", "succeed",
    "success", "such", "suddenly", "suffer", "suffix", "sugar", "suggest", "suggested",
    "suit", "summer", "sun", "supply", "support", "suppose", "sure", "surface", "surprise",
    "swim", "syllables", "symbols", "system", "table", "tail", "take", "talk", "tall", "tape",
    "task", "tax", "teach", "teacher", "team", "tear", "technology", "television", "tell",
    "temperature", "ten", "tend", "term", "terms", "test", "than", "thank", "that", "the",
    "theater", "their", "them", "themselves", "then", "thence", "theory", "there", "these",
    "they", "thick", "thin", "thing", "think", "third", "thirty", "this", "those", "thou",
    "though", "thought", "thousand", "thousands", "threat", "three", "through", "throw",
    "thus", "ticket", "tied", "tight", "time", "tiny", "tired", "title", "to", "today",
    "together", "told", "tone", "tongue", "too", "took", "tools", "top", "total", "touch",
    "tough", "tour", "toward", "town", "track", "trade", "tradition", "train", "training",
    "travel", "treat", "treatment", "tree", "trial", "triangle", "trick", "trip", "troop",
    "trouble", "truck", "true", "trust", "truth", "try", "tube", "twice", "two", "type",
    "ugly", "uncle", "under", "underline", "understand", "union", "unit", "unite",
    "university", "unless", "until", "up", "upon", "us", "use", "usual", "usually", "valley",
    "value", "various", "verb", "very", "victim", "view", "village", "violence", "visit",
    "voice", "vote", "vowel", "wait", "walk", "wall", "want", "war", "warm", "was", "wash",
    "wasn't", "waste", "watch", "watched", "watches", "watching", "water", "wave", "waves",
    "way", "we", "we'll", "wear", "weather", "wedding", "week", "weight", "welcome", "well",
    "went", "were", "west", "western", "what", "whatever", "wheel", "wheels", "when",
    "whenever", "where", "wherever", "whether", "which", "while", "whisper", "white", "who",
    "whole", "whom", "whose", "why", "wide", "wife", "wild", "will", "willing", "win", "wind",
    "window", "wine", "wing", "wings", "winner", "winter", "wire", "wise", "wish", "with",
    "within", "without", "woman", "women", "won't", "wonder", "wood", "word", "work",
    "worker", "workers", "world", "worry", "worse", "worst", "worth", "would", "wouldn't",
    "wound", "wrap", "write", "writer", "written", "wrong", "wrote", "yard", "yeah", "year",
    "yell", "yellow", "yes", "yesterday", "yet", "you're", "young", "younger", "youngest",
    "your", "yourself", "zero", "zone",
}
